{{- if .Values.ingress.enabled -}}
{{- $fullName := include "test-chart.fullname" . -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "test-chart.fullname" . }}
spec:
  domains:
    - "test.genai.samp.solutions"
{{- end }}
